/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println("Sum of 2 and 3 is "
        + new Calculate().sum(2, 3)
        + ". Average is "
        + new Calculate().average(2, 3)
        + ".");
    System.out.println("Sum of 1 to 10 is "
        + new Calculate().sumRange(1, 10)
        + ". Average is "
        + new Calculate().avgRange(1, 10)
        + ".");
    System.out.println("Sum of odd of 1 to 10 is "
        + new Calculate().oddSum(1, 10)
        + ".");
    System.out.println("Sum of even of 1 to 10 is "
        + new Calculate().evenSum(1, 10)
        + ".");

  }
}
